#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: E:/log/sell.log
#  file: E:/log
#  level:
#    com.imooc.LogTest: debugspring:
spring:
#配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.179.133/shop?characterEncoding=utf-8&useSSL=false
#配置jpa
  jpa:
    database: mysql
#    是否显示生产的数据
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
#        注意这个一定要配置mysql的方言
    database-platform: org.hibernate.dialect.MySQL5Dialect